
import React from 'react';

interface GeneratedImageProps {
  src: string;
}

export const GeneratedImage: React.FC<GeneratedImageProps> = ({ src }) => {
  return (
    <div className="w-full max-w-lg mx-auto">
      <img
        src={src}
        alt="Generated by AI"
        className="rounded-lg shadow-2xl shadow-cyan-500/20 object-contain w-full h-full"
      />
    </div>
  );
};
